- op: replace
  path: /spec/template/spec/containers/0/image
  value: ghcr.io/mlibrary/aspace-containerization/aspace-spcoll@sha256:sha256:6314287388c5d56a07d0f83ca5d4bb715d2834d9ee820d261add7500c9e7cc35
